import 'package:flutter_trello/models/list.dart';
import 'package:flutter_trello/models/todo.dart';

List<ListModel> listsSeed = [
  ListModel(
    title: "Backlog",
    todos: [
      TodoModel(
        title: "todo 1",
        description: "awesome todo",
        list: [
          ChecklistModel(description: "item 1", done: false),
          ChecklistModel(description: "item 1", done: false),
          ChecklistModel(description: "item 1", done: false),
          ChecklistModel(description: "item 1", done: false),
          ChecklistModel(description: "item 1", done: false),
          ChecklistModel(description: "item 1", done: false),
          ChecklistModel(description: "item 1", done: false),
          ChecklistModel(description: "item 1", done: false),
          ChecklistModel(description: "item 1", done: false),
          ChecklistModel(description: "item 1", done: false),
          ChecklistModel(description: "item 1", done: false),
          ChecklistModel(description: "item 1", done: false),
        ],
      ),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
    ],
  ),
  ListModel(
    title: "Accepted",
    todos: [
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
    ],
  ),
  ListModel(
    title: "In Progress",
    todos: [
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
    ],
  ),
  ListModel(
    title: "Verification",
    todos: [
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
    ],
  ),
  ListModel(
    title: "Done",
    todos: [
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
      TodoModel(title: "todo 1", description: "awesome todo", list: []),
    ],
  ),
];
